- name: Add node-exporter jobs under scrape_configs
  ansible.builtin.blockinfile:
    path: /etc/prometheus/prometheus.yml
    marker: "# {mark} ANSIBLE MANAGED NODE JOBS"
    insertafter: '^scrape_configs:'
    block: |
      {% for h in groups['workers'] %}
        - job_name: "node-{{ hostvars[h].inventory_hostname }}"
          static_configs:
            - targets:
                - "{{ hostvars[h].ansible_host }}:9100"
      {% endfor %}
  notify: Reload Prometheus
  become: true